import '@/styles/global.scss';
import Header from '@/containers/common/header';
import RecoilRootProvider from '@/utils/recoilRootProvider';

export const metadata = {
  title: 'Ah-whew',
  description: 'Generated by Next.js',
};

declare global {
  interface Window {
    kakao: any;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        {/* 헤더 푸터 커스텀 해야함 */}
        <main>
          <RecoilRootProvider>
            <Header />
            {children}
          </RecoilRootProvider>
        </main>
        <script src="https://developers.kakao.com/sdk/js/kakao.js" />
      </body>
    </html>
  );
}
